"""Tailored Resume: per-job resume content grounded in evidenced profile facts,
the job's requirements, and the latest fit analysis. Mirrors the pitch
pipeline (claim -> close conn -> LLM -> reopen -> versioned insert). Contact
details (name, email, phone) are injected at RENDER time from your profile,
never generated by the model — see render_markdown/render_html/render_text."""

import json
import logging

from app import db as dberr

from app.db import get_conn
from app.llm.base import LLMError, get_provider
from app.llm.prompts import RESUME_SYSTEM, resume_prompt
from app.models.extraction import ResumeResult
from app.services.profile import (
    direction_block_for_prompt,
    has_profile_facts,
    profile_block_for_prompt,
)
from app.user_errors import USER_ERROR_GENERIC, USER_ERROR_RACE
from app.web import templates

log = logging.getLogger(__name__)


def latest_resume(job_id: int):
    conn = get_conn()
    try:
        return conn.execute(
            "SELECT * FROM resumes WHERE job_id = ? ORDER BY version DESC LIMIT 1",
            (job_id,),
        ).fetchone()
    finally:
        conn.close()


def _fit_block(fit) -> str:
    """Compact plaintext of the latest fit analysis for the resume prompt."""
    if fit is None:
        return ""
    lines = [f"score: {fit['score']}/100 ({fit['band']})"]
    for s in json.loads(fit["strengths_json"]):
        lines.append(f"strength: {s['requirement']} — {s['evidence']}")
    for g in json.loads(fit["gaps_json"]):
        lines.append(f"gap ({g['importance']}): {g['requirement']} — {g['why']}")
    return "\n".join(lines)


def run_resume(job_id: int) -> None:
    """Write a new versioned resume for the job (background task)."""
    conn = get_conn()
    try:
        job = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
        if job is None or job["extract_status"] != "ready":
            return
        if not has_profile_facts(job["user_id"]):
            # Nothing evidenced to write from — don't fabricate a resume.
            # Leave status 'none'; the tab prompts for a profile.
            conn.execute(
                "UPDATE jobs SET resume_status = 'none', resume_error = NULL WHERE id = ?",
                (job_id,),
            )
            conn.commit()
            return
        requirements = conn.execute(
            "SELECT * FROM job_requirements WHERE job_id = ? ORDER BY kind, skill",
            (job_id,),
        ).fetchall()
        fit = conn.execute(
            "SELECT * FROM fit_analyses WHERE job_id = ? ORDER BY version DESC LIMIT 1",
            (job_id,),
        ).fetchone()

        conn.execute(
            "UPDATE jobs SET resume_status = 'running', resume_error = NULL, "
            "busy_since = datetime('now') WHERE id = ?",
            (job_id,),
        )
        conn.commit()
    finally:
        conn.close()

    job_summary = " | ".join(
        str(v)
        for v in (job["title"], job["company"], job["seniority"], job["sector"], job["location"])
        if v
    )
    requirements_block = "\n".join(
        f"- ({r['kind']}) {r['skill_display']}"
        + (f" [{r['level']}]" if r["level"] else "")
        + (f' — "{r["evidence_text"]}"' if r["evidence_text"] else "")
        for r in requirements
    )

    # The provider round-trip can take minutes — no pooled connection is held.
    try:
        result: ResumeResult = get_provider().extract(
            system=RESUME_SYSTEM,
            prompt=resume_prompt(
                job_summary,
                requirements_block,
                profile_block_for_prompt(job["user_id"]),
                _fit_block(fit),
                direction_block_for_prompt(job["user_id"]),
            ),
            schema=ResumeResult,
        )
    except LLMError as exc:
        log.warning("resume for job %s failed: %s", job_id, exc)
        conn = get_conn()
        try:
            conn.execute(
                "UPDATE jobs SET resume_status = 'error', resume_error = ? WHERE id = ?",
                (str(exc), job_id),  # LLMError copy is curated at the provider
            )
            conn.commit()
        finally:
            conn.close()
        return

    conn = get_conn()
    try:
        try:
            content_json = result.model_dump_json()
            for _ in range(5):
                version = conn.execute(
                    "SELECT COALESCE(MAX(version), 0) + 1 FROM resumes WHERE job_id = ?",
                    (job_id,),
                ).fetchone()[0]
                try:
                    conn.execute(
                        "INSERT INTO resumes (job_id, version, content_json) VALUES (?, ?, ?)",
                        (job_id, version, content_json),
                    )
                    break
                except dberr.ForeignKeyViolation:
                    conn.rollback()  # job deleted mid-run — nothing to store
                    return
                except dberr.UniqueViolation:
                    conn.rollback()  # version race with a concurrent run; retry
                    continue
            else:
                log.warning("resume for job %s exhausted version retries", job_id)
                conn.rollback()
                conn.execute(
                    "UPDATE jobs SET resume_status = 'error', resume_error = ? WHERE id = ?",
                    (USER_ERROR_RACE, job_id),
                )
                conn.commit()
                return
            conn.execute("UPDATE jobs SET resume_status = 'ready' WHERE id = ?", (job_id,))
            conn.commit()
        except Exception:
            # Any unexpected failure must reach a terminal 'error' status.
            log.exception("resume for job %s failed unexpectedly", job_id)
            conn.rollback()
            conn.execute(
                "UPDATE jobs SET resume_status = 'error', resume_error = ? WHERE id = ?",
                (USER_ERROR_GENERIC, job_id),
            )
            conn.commit()
            return
    finally:
        conn.close()


# ─────────────────────────────────────────────────────────────────────────────
# Renderers: content_json + real job/user data -> each downloadable format.
# render_html backs BOTH the standalone "view in new tab" route and the
# format=html download — one Jinja template (resume_print.html), one flag
# (`printable`) toggling the print-button chrome, so the resume layout is
# defined exactly once.
# ─────────────────────────────────────────────────────────────────────────────


def render_html(content: dict, job, user, *, printable: bool = False) -> str:
    return templates.env.get_template("resume_print.html").render(
        content=content, job=job, user=user, printable=printable
    )


def _date_range(start: str | None, end: str | None) -> str:
    if not start and not end:
        return ""
    return f"{start or '?'} – {end or 'present'}"


def _contact_line(user, job) -> str:
    """The one line under the name: whatever contact details are filled in on
    the Settings page, plus the job's location. Blank fields are skipped, so an
    unset profile just prints a name."""
    return " | ".join(
        p for p in (user["contact_email"], user["contact_phone"], job["location"]) if p
    )


def render_markdown(content: dict, job, user) -> str:
    lines = [f"# {user['name'] or 'Resume'}"]
    contact = _contact_line(user, job)
    if contact:
        lines.append(contact)
    if content.get("headline"):
        lines.append(f"\n**{content['headline']}**")
    lines.append(f"\n## Summary\n\n{content.get('summary', '')}")
    if content.get("skills"):
        lines.append("\n## Skills\n")
        for g in content["skills"]:
            lines.append(f"- **{g.get('category', '')}:** {', '.join(g.get('items', []))}")
    if content.get("experience"):
        lines.append("\n## Experience")
        for e in content["experience"]:
            header = e.get("title", "")
            if e.get("organization"):
                header += f" — {e['organization']}"
            lines.append(f"\n### {header}")
            dates = _date_range(e.get("start_date"), e.get("end_date"))
            if dates:
                lines.append(f"*{dates}*\n")
            for b in e.get("bullets", []):
                lines.append(f"- {b}")
    if content.get("education"):
        lines.append("\n## Education")
        for ed in content["education"]:
            header = ed.get("degree", "")
            if ed.get("institution"):
                header += f" — {ed['institution']}"
            lines.append(f"\n**{header}**")
            dates = _date_range(ed.get("start_date"), ed.get("end_date"))
            if dates:
                lines.append(f"*{dates}*")
            if ed.get("detail"):
                lines.append(ed["detail"])
    if content.get("certifications"):
        lines.append("\n## Certifications")
        for c in content["certifications"]:
            piece = c.get("name", "")
            if c.get("organization"):
                piece += f" — {c['organization']}"
            if c.get("date"):
                piece += f" ({c['date']})"
            lines.append(f"- {piece}")
    if content.get("projects"):
        lines.append("\n## Projects")
        for p in content["projects"]:
            lines.append(f"\n**{p.get('name', '')}**")
            if p.get("detail"):
                lines.append(p["detail"])
            for b in p.get("bullets", []):
                lines.append(f"- {b}")
    return "\n".join(lines) + "\n"


def render_text(content: dict, job, user) -> str:
    # Same section order as markdown, plain-ASCII headers (ATS-copy-paste safe).
    lines = [user["name"] or "Resume"]
    contact = _contact_line(user, job)
    if contact:
        lines.append(contact)
    if content.get("headline"):
        lines.append(content["headline"])
    lines.append("\nSUMMARY\n" + content.get("summary", ""))
    if content.get("skills"):
        lines.append("\nSKILLS")
        for g in content["skills"]:
            lines.append(f"{g.get('category', '')}: {', '.join(g.get('items', []))}")
    if content.get("experience"):
        lines.append("\nEXPERIENCE")
        for e in content["experience"]:
            header = e.get("title", "")
            if e.get("organization"):
                header += f" — {e['organization']}"
            dates = _date_range(e.get("start_date"), e.get("end_date"))
            lines.append(f"\n{header}" + (f" ({dates})" if dates else ""))
            for b in e.get("bullets", []):
                lines.append(f"  - {b}")
    if content.get("education"):
        lines.append("\nEDUCATION")
        for ed in content["education"]:
            header = ed.get("degree", "")
            if ed.get("institution"):
                header += f" — {ed['institution']}"
            dates = _date_range(ed.get("start_date"), ed.get("end_date"))
            lines.append(header + (f" ({dates})" if dates else ""))
            if ed.get("detail"):
                lines.append(f"  {ed['detail']}")
    if content.get("certifications"):
        lines.append("\nCERTIFICATIONS")
        for c in content["certifications"]:
            piece = c.get("name", "")
            if c.get("organization"):
                piece += f" — {c['organization']}"
            if c.get("date"):
                piece += f" ({c['date']})"
            lines.append(f"  - {piece}")
    if content.get("projects"):
        lines.append("\nPROJECTS")
        for p in content["projects"]:
            lines.append(p.get("name", ""))
            if p.get("detail"):
                lines.append(f"  {p['detail']}")
            for b in p.get("bullets", []):
                lines.append(f"  - {b}")
    return "\n".join(lines) + "\n"
