"""Where uploaded files live.

Everything you upload is written under ``JOBPREP_DATA_DIR/uploads`` as
``<uuid>.<ext>``; ``documents.path`` holds that bare key, never an absolute
path, so moving or copying the data directory doesn't break existing rows.

This stays a seam (rather than direct ``open()`` calls in the services) so a
fork that wants object storage has exactly one class to add — and so tests can
point it at a temp directory.
"""

import logging
import threading
from pathlib import Path

from app.config import UPLOADS_DIR

log = logging.getLogger(__name__)


class LocalStorage:
    """Files under UPLOADS_DIR. Keys are bare names; an absolute path is
    honored as-is so a hand-edited row keeps working."""

    def __init__(self, root: Path | None = None):
        self.root = root or UPLOADS_DIR

    def _path(self, key: str) -> Path:
        p = Path(key)
        if p.is_absolute():
            return p
        # Keys are generated by the app, but never let one climb out of the
        # uploads directory even so.
        return self.root / Path(key).name

    def save(self, key: str, content: bytes) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        self._path(key).write_bytes(content)

    def read(self, key: str) -> bytes:
        try:
            return self._path(key).read_bytes()
        except OSError as exc:
            raise FileNotFoundError(key) from exc

    def delete(self, key: str) -> None:
        try:
            self._path(key).unlink(missing_ok=True)
        except OSError:
            # Deletion is cleanup, never load-bearing: the row is already gone.
            log.exception("failed to delete upload %s", key)


_storage: LocalStorage | None = None
_storage_lock = threading.Lock()


def get_storage() -> LocalStorage:
    """The process-wide storage backend."""
    global _storage
    if _storage is None:
        with _storage_lock:
            if _storage is None:
                _storage = LocalStorage()
    return _storage
